### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by antoine1fr** [rgrinberg/ocaml-mustache#16]
You do mention the MIT license in the _oasis and opam files, but you do not embed the license's text into your source files.

I needed to copy/paste some of the source files in my code base so I added the license text as found [here][1] in them, with your full name and the year 2015. Are you okay with it?

[1]: http://choosealicense.com/licenses/mit/

**Comment by rgrinberg** [comment]
I'm fine with it.

**Comment by rgrinberg** [comment]
License files have been added to the source. Let me know if there's anything else I need to do.
