### ISSUE TITLE
Online HTML docs

### ISSUE THREAD

**Issue by Armael** [rgrinberg/ocaml-mustache#32]
It would be nice to put the ocamldoc-generated docs of the API online. For that we need a `make doc` target, and I don't know how to do that with jbuilder.

**Comment by rgrinberg** [comment]
This shouldn't be very hard: http://jbuilder.readthedocs.io/en/latest/api-doc.html#api-documentation

But I  don't yet have odoc installed.

**Comment by avsm** [comment]
if #38 is merged and `dune-release` is used, then online docs should appear now.

**Comment by psafont** [comment]
Now that doc generation has been fixed on the latest commit, docs should appear once the next version in https://ocaml.org/p/mustache/latest/doc/index.html

**Comment by psafont** [comment]
I can see that the docs are published as expected
