### ISSUE TITLE
Is it possible to make mustache_cli available via OPAM?

### ISSUE THREAD

**Issue by anton-trunov** [rgrinberg/ocaml-mustache#35]

**Comment by rgrinberg** [comment]
Do you mean the binary or the module? We are planning on a `mustache-unix` sub package to put all the unix related functionality. I guess where such a binary could go

**Comment by anton-trunov** [comment]
Yes, the binary :) Sorry for not being clear.

**Comment by avsm** [comment]
created a mustache-unix package in #38

**Comment by anton-trunov** [comment]
Fixed by #39
