### ISSUE TITLE
command-line output

### ISSUE THREAD

**Issue by gmcninch** [rgrinberg/ocaml-mustache#43]
Hi, 

Currently -- (i.e. with

```
> george@calliope:~$ opam list | grep mustache
> mustache                      3.1.0       Mustache logic-less templates in OCaml 
```
)

if I do
```
$ mustache foo.json bar.template
```

then as specified in `mustache_cli.ml` the result is to first `print_endline` the content of `foo.json`, followed by the output of  `apply_mustache`.

Outputting the json at the top feels a bit like a debugging step that wasn't removed, though maybe there is some reason you want to see this bit in the output? Anyhow, I happened to find a use for the tool and noticed this property. (The extra "json" actually gave me a motive to learn to use `sed` to snip the stuff at the top of the output -- somehow I'd always avoided `sed` til now!  )

Anyhow, I thought I'd report the matter.

Thanks, and all the best,
george

**Comment by Armael** [comment]
I'm not sure there's a good reason (other maintainers: is there?). Would you be willing to submit a PR turning the printing of the JSON as a command-line option? (that would be disabled by default)

**Comment by rgrinberg** [comment]
I can't think of a good reason either.

**Comment by gmcninch** [comment]
@Armael: I just made a pull request which does what you indicate (I'm pretty sure). 

(I'm a bit new using github - hopefully I've done things the right way? Let me know if not...)

**Comment by gasche** [comment]
Since #54 was merged, the JSON is not printed anymore.
