### ISSUE TITLE
Sexplib dependency?

### ISSUE THREAD

**Issue by sagotch** [rgrinberg/ocaml-mustache#6]
I do not understand what is sexplib used for.

Could not it be removed?

**Comment by rgrinberg** [comment]
It was mostly useful for debugging for me personally. Someone might rely on it for pretty printing however. I wouldn't mind doing my small part in killing camlp4 by getting rid of it.

cc @toby-m and @mk270 in case it's going to break any of your code.

**Comment by tmo-trustpilot** [comment]
No, I have no need of it.

**Comment by rgrinberg** [comment]
OK getting rid of it.

**Comment by mk270** [comment]
me neither; thanks for the headsup
