### ISSUE TITLE
consider changing the binary name?

### ISSUE THREAD

**Issue by gasche** [rgrinberg/ocaml-mustache#61]
Currently `mustache_cli.ml` is installed as a `mustache` binary in the user PATH. This is a natural choice that is easy for users to guess, but it has the downside of conflicting with the binary name chosen by... any other Mustache implementation. For example, the original implementation in Ruby provides the [mustache(1)](https://mustache.github.io/mustache.1.html) command that is easy to find over the net. If you run `gem install mustache`, it installs a Ruby library and also a `mustache` binary. (When trying to compare the behavior of the two tools, I would keep uninstalling and reinstalling the Ruby tool to avoid name conflicts.)

Should one consider changing the name of the OCaml tool to avoid naming conflicts with other implementations? I'm not saying that the name should change, but I'm creating this issue to get an idea of what people (and in particular @rgrinberg) think.

Naming conflicts are maybe not much of an issue, given that most users are going to use just one tool anyway. But some systems/distributions want to avoid conflicts globally; if someone someday decided to package `ocaml-mustache` for Debian, then the naming clash would be an annoying issue to deal with.

My only idea for an alternative name would be `mustacho`, which sounds somewhat like a contraction of "mustache in OCaml", and is an alternative spelling for "mustache" in some languages (in English it exists, but "mustachio" is more commonly used; it exists in some variants of Spanish but "mostacho" is more common, etc.). (I'm afraid that camels don't have mustaches; search for this on the web led me to the Mustache Contest at the Pushkar Camel Fair, which does not bring any clear name suggestion.)

**Comment by gasche** [comment]
(Cc @anton-trunov who, if I understand correctly, proposed to export `mustache_cli` as a user-installed binary in #35 and #39; and @strub who hacked on the tool recently and may have an opinion.)

**Comment by rgrinberg** [comment]
I don't have a strong opinion as the binary was only introduced to simplify testing the library. No standalone usage was intended. 

The naming conflict isn't a big deal because these moustache binaries seem to be interchangeable. However, one advantage of picking silly name like mustacheo is that we can pick a package name that matches it for the binary.

**Comment by Drup** [comment]
`moustache`, évidement. :)

**Comment by gasche** [comment]
We didn't manage to get much feedback on this issue, but I would still be in favor of `mustacho`. I think that `moustache` is too close (it's just a typo away) so that it may not be recognized/understood as a different name, and also I don't know if we need the OCaml ecosystem to feel more French than it already is :-)

**Comment by Drup** [comment]
Didn't you learned yet ? Innocuous usage of french is endearing. ;)

Just use `mustache-ml`/`mustache_ml`/`mustache.ml` then. `mustacho` sounds like a bad cartoonish italian impersonation.

**Comment by gasche** [comment]
I was going to say that I like `mustache.ml`, but actually I think that (while on Windows `mustache.ml.exe` may be fine) using the `.ml` extension for a binary is too confusing. My favorite choice in your proposals is `mustache-ml`: I don't like it but I don't dislike it either, so I guess that's a compromise.

**Comment by gasche** [comment]
(why non just `mustache-ocaml` ? it's just one auto-complete away anyway)

**Comment by Armael** [comment]
I think `mustache-ocaml` is quite fine indeed.
